# Generated by Django 5.1.1 on 2024-10-05 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_pincode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='color',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='size',
        ),
    ]
